version: '3.0'
services:
  salmanhaljido_server:
    image: salmanhaljido_server
    ports:
      - "9091:8080"
    container_name: salmanhaljido_server_blue
  mongo:
    image: mongo:4.2
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=openapi
