const categoryList = {
  교통: [
    // { publicTransportationUtilizationRate: "대중교통 이용률" },
    // { station: "대중교통 정류장" },
    { electricVehicleCharging: "전기차 충전소" },
    { parkinglot: "공용, 민영주차장" },
  ],
  재난: [{ shelter: "민방위 대피소" }],
  안전: [
    { carAccident: "낮은 교통사고 빈도" },
    { crime: "낮은 범죄율" },
    { childSafety: "어린이 보호구역" },
    { femaleSafety: "여성안심" },
  ],
  의료: [{ hospital: "의료기관" }, { drugStore: "약국" }],
  반려동물: [{ animalHospital: "동물병원" }, { animalBeauty: "동물미용" }],
  교육: [
    // { kindergarden: "유치원" },
    { school: "초, 중, 고등학교" },
    { academy: "학원 및 교습소" },
  ],
  문화: [
    { entertainment: "미술관, 박물관" },
    { theater: "영화관" },
    { library: "도서관" },
    { concertHall: "공연장" },
    { sportsFacilities: "스포츠시설" },
  ],
  생활: [
    // { restaurant: "음식점" },
    { park: "공원" },
    { mart: "마트, 시장" },
    { facilitiesForTheDisabled: "장애인 편의시설" },
  ],
};

const categoryDetail = {
  // publicTransportationUtilizationRate: "대중교통 이용률",
  // station: "대중교통 정류장",
  electricVehicleCharging: "전기차 충전소",
  parkinglot: "공용, 민영주차장",
  shelter: "민방위 대피소",
  carAccident: "교통사고",
  crime: "범죄",
  childSafety: "어린이 보호구역",
  femaleSafety: "여성안심",
  hospital: "의료기관",
  drugStore: "약국",
  animalHospital: "동물병원",
  animalBeauty: "동물미용",
  // kindergarden: "유치원",
  school: "초, 중, 고등학교",
  academy: "학원 및 교습소",
  entertainment: "미술관, 박물관",
  theater: "영화관",
  library: "도서관",
  concertHall: "공연장",
  sportsFacilities: "스포츠시설",
  // restaurant: "음식점",
  park: "공원",
  mart: "마트, 시장",
  facilitiesForTheDisabled: "장애인 편의시설",
};

export { categoryList, categoryDetail };
